services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development

    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - ./files:/usr/src/app/files
    command: npm run start:dev
    env_file:
      - .env.development
    ports:
      - 3000:3000
    depends_on:
      - postgres-db
  postgres-db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=devotel
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - '8080:80'
    depends_on:
      - postgres-db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
