version: '3.8'

services:
  postgres_db:
    image: postgres:13
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: testdb
    ports:
      - '5432:5432'
    networks:
      - test-network
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app-test
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=testuser
      - DB_PASSWORD=testpassword
      - DB_NAME=testdb
    depends_on:
      - postgres_db
    networks:
      - test-network
    command: ['npm', 'run', 'test']

networks:
  test-network:
    driver: bridge

volumes:
  postgres_test_data:
